server:
  port: 8888
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: spring-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

# Spring Security Config
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    org.springframework: INFO